---
output:
  html_document:
    theme: united
    highlight: pygments
#    toc: true
#    toc_float: true
#    toc_collapsed: true
#    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Markdown - primeiros passos

\


## **Formatação de Texto**

\

#### **Tamanho**

O tamanho da texto é controlado com o número de caracteres \# que o precedem.

Ex.:

* # \# teste
* ## \#\# teste
* ### \#\#\# teste
* #### \#\#\#\# teste
* ##### \#\#\#\#\# teste
* ###### \#\#\#\#\# teste

\

#### **Itálico**
Escre-se o texto entre asteríscos (\*texto\*)  ou entre underscores (\_texto\_).

Ex.: *teste*    

\

#### **Negrito**

Escre-se o texto entre asteríscos duplos (\*\*texto\*\*)  ou entre underscores duplos (\_\_texto\_\_).

Ex. **teste**

\

#### **Código**

Escreve-se o código entre crases (\`código\`). 

Ex.: `ggplot()+geom_point()`

\
Gerando bloco de código:

\`\`\` \ 
BLOCO \
\`\`\`

#### **Latex**

Escreve-se o código latex entre cifrões (\$código\$):

Ex.: $\partial_{\mu}F^{\mu\nu} = J^\nu$

\

#### **Listas**

\

**Bullet**

Utiliza-se \* ou - na frente de cada item:\
Ex.: 

```
* item 1
* item 2
- item 3
```
gera:

* item 1
* item 2
- item 3

**Numerais arábicos**

Utiliza-se 1. na frente de cada item (a numeração é automática):\
Ex.:
```
1. item 1
1. item 2
1. item 3
```
gera:

1. item 1
1. item 2
1. item 3

**Numerais romanos**

Utiliza-se i. na frente de cada item (a numeração é automática):\
Ex.:
```
i. item 1
i. item 2
i. item 3
```
gera:

i. item 1
i. item 2
i. item 3

**Letras**

Utiliza-se a. na frente de cada item:\
Ex.:
```
a. item 1
a. item 2
a. item 3
```
gera:

a. item 1
a. item 2
a. item 3

#### **Sublistas**

Utiliza-se 4 espaços para a criação de uma sublista.\
Ex.:
```
a. item 1
a. item 2
    1. item 2.1
    1. item 2.2
    1. item 2.3
a. item 3
```
gera:

a. item 1
a. item 2
    1. item 2.1
    1. item 2.2
    1. item 2.3
a. item 3

\

#### **Tabelas**
```
coluna 1 |coluna 2 | coluna 3 
---|--- | ---
item 1.1 |  item 1.2 | item 1.3
item 2.1 |  item 2.2 | item 1.2
```
gera:

coluna 1 |coluna 2 | coluna 3 
---|--- | ---
item 1.1 |  item 1.2 | item 1.3
item 2.1 |  item 2.2 | item 1.2